### ISSUE TITLE
[Bug]: Speed boost issue on smart fridge

### ISSUE THREAD

**Issue by Duskrat** [Blue-Guy-Entertainment/wobbler-hub#5]
### What happened?

I'm never gaining any speed when going through the speedbost in Easy 09, I would expect it to give me the speed it gives. Other speedbo0sts work, it's only Easy 09. (short gif)

### Game Version

v0.2.1

### Operating System & Version

Samsung

### CPU & GPU info

36" BESPOKE 3 Door French Door Refrigerator with Autofill Pitcher

### Relevant log output

```shell
Insert your log output here..
  scene/resources/resource_format_text.cpp:453 - res://scenes/standalone/autoload.tscn:28 - ext_resource, invalid UID: uid://bgqggs0h87vps - using text path instead: res://preloadables/assets/stats/energy.tres
  scene/resources/resource_format_text.cpp:453 - res://scenes/ui_game/tokens/token_special.tscn:5 - ext_resource, invalid UID: uid://bgqggs0h87vps - using text path instead: res://preloadables/assets/stats/energy.tres
```

**Comment by BlueGuyEntertainment** [comment]
Bruh
